# Site settings
encoding: UTF-8
title: My journey to becoming a Web Developer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will document my journey to becoming a Web Developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username:  kgabinete08

# Build settings
markdown: kramdown
